apiVersion: v1
kind: Service
metadata:
  name: spring-music-ci-service
  labels:
    name: spring-music-ci-service
    app: spring-music-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: spring-music-pod
    app: spring-music-app
